### PR TITLE
compiler flags necessary for AIX

### PR DESCRIPTION
**Pull request by jeremymv2**
### :nut_and_bolt: Description

We discovered some compiler flags necessary for gem usage on AIX platforms.
This has been tested successfully in our environment:

```
========================================
= Tool Versions on aix aix-7 x86_64 builder powerpc
========================================

Bash.........GNU bash, version 4.3.30(1)-release (powerpc-ibm-aix6.1.0.0)
Bundler......Bundler version 1.16.0
XLC..........IBM XL C/C++ for AIX, V13.1 (5725-C72, 5765-J07)
Git..........git version 2.14.1
Make.........GNU Make 4.1
Ruby.........ruby 2.4.2p198 (2017-09-14 revision 59899) [powerpc-aix6.1.0.0]
RubyGems.....2.6.14
```

### :white_check_mark: Checklist

- [x] Code actually executed - gem native extensions compile?
- [x] Vetting performed (unit tests, lint, etc.)?

Signed-off-by: Jeremy J. Miller <jm@chef.io>

### CODE REVIEW

**Comment by jeremymv2** [comment]
@knu can you take a look at this PR please when you have time?
It fixes https://github.com/chef/inspec/issues/2873 for us.

❤️

**Comment by knu** [comment]
Thanks!  I've resolved a conflict, so please check out if it still works!

**Comment by jeremymv2** [comment]
@knu this looks perfect, so thank you very much!

We will revert back to your gem soon as you are able to release to rubygems.  Will that be soon?

giphy

**Comment by jquick** [comment]
@knu any news on a new rubygems push with these new patches?

**Pull request merged**
