### PR TITLE
Add Ruby 2.3.0

### PR DESCRIPTION
**Pull request by marshall-lee**

### CODE REVIEW

**Comment by knu** [comment]
Thanks.  I'll partly merge this, I'm not going to drop support for 1.8 in minor updates.

**Comment by marshall-lee** [comment]
@knu I can revert this commit but then I should restrict `test-unit` version to one that still supports `1.8`

**Comment by marshall-lee** [comment]
...because `test-unit` developers aleady dropped `ruby 1.8.7` support in a minor relase `3.1.6`

**Comment by marshall-lee** [comment]
@knu it's okay now, i can rebase if you want.

**Pull request merged**
