### PR TITLE
Fix table type regression on ARM

### PR DESCRIPTION
**Pull request by nomoon**
Fixes regression in #15 caused by Unicode 9.0 table.hh update.

### CODE REVIEW

**Comment by knu** [comment]
This was unfortunate.  Could you submit this to the upstream as well so it never happens again?

**Comment by nomoon** [comment]
@knu Is there any reason this signedness fix might cause problems upstream? Is it just the one explicit `signed char` that's the issue?

**Comment by nomoon** [comment]
I see at https://github.com/knu/ruby-unf_ext/commit/8a6a735b51ef903200fc541112e35b7cea781856#diff-634ecdeb8757b51ad1aabc3a8b0bb6a3R20 you're also doing a cast to `const char *`, should I submit that change upstream as well?

**Comment by nomoon** [comment]
My only concern is whether the `(const char *)` cast in `normalizer.hh` (so that the Strings table is accepted by the Trie class) causes the code to compile fine on ARM, but not actually work. Do we have confirmation that the normalization tests were passing on ARM in addition to it compiling?

**Comment by marcust** [comment]
The version on the `fix_table_type` branch builds for me

**Comment by nomoon** [comment]
@marcust Any chance you also did `rake test`?

**Comment by nomoon** [comment]
@knu upstream PR submitted.

**Comment by knu** [comment]
Great, thanks!  Let's see it dealt with and then I'll merge this soon.

**Comment by nomoon** [comment]
Looks like sile/unf#2 was accepted upstream.

**Pull request merged**
